spring:
  application:
    name: process-pix-transaction
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  websocket:
    enabled: true
    messaging:
      broker:
        relay:
          enabled: false
  config:
    import: optional:file:docs/secrets.yaml

otel:
  service:
    name: process-pix-transaction
  exporter:
    otlp:
      endpoint: https://otlp.nr-data.net:4317
      headers:
        api-key: ${NEW_RELIC_API_KEY:dummy}
  resource:
    attributes:
      deployment.environment: test
      service.namespace: pix

management:
  tracing:
    enabled: true



